name: AutoParkourLite
author: Hellgast23
version: 2.0.0
main: me.spigot.hellgast23.autoparkourlite.MainPlugin

commands:
  autoparkourlite:
    usage: /autoparkourlite
    aliases: [apl]
    description: Start the parkour.

permissions:
  autoparkourlite.start:
    default: op
    description: Start a new auto parkour.